name: CI/CD Pipeline - noisier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ingestbot
      DOCKER_IMAGE_NAME: noisier_alt

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Lint Code
      run: |
        flake8 .

    - name: Run tests
      run: |
        # pytest tests/test_main.py -vv
        PYTHONPATH=. pytest tests/test_main.py -vv

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . -t noisier

    - name: Run the Docker container | capture logs | verify Successful Visits
      run: |
          container_id=$(docker run -d noisier)
          timeout=180
          interval=5
          elapsed=0

          while [ "$elapsed" -lt "$timeout" ]; do
              if docker logs "$container_id" 2>&1 | grep -q "Successful Visits"; then
                  echo "PASS"
                  exit 0
              fi
              sleep "$interval"
              elapsed=$((elapsed + interval))
          done

          echo "FAIL: Successful Visits not found within the timeout period."
          docker logs "$container_id"
          exit 1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}.slice(0, 7)
